apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test
  title: Test
spec:
  owner: administrator
  type: platform.digando.io
  parameters:
    - title: Database parameters
      type: object
      properties:
      
        group:
          type: string
          ui:widget: hidden
          default: platform.digando.io
        version:
          type: string
          ui:widget: hidden
          default: v1alpha1
        kind:
          type: string
          ui:widget: hidden
          default: Database
        plural:
          type: string
          ui:widget: hidden
          default: databases
        metadata:
          title: Metadata
          type: object
          required:
            - name
          properties:
            name:
              title: Database name
              type: object
              ui:field: EntityObjectPicker
              ui:options:
                labelVariant: primaryTitle
            annotations:
              title: Annotations
              type: object
              properties:
                backstage.io/title:
                  title: Database title
                  type: string
                backstage.io/plural:
                  type: string
                  ui:widget: hidden
                  default: databases
    - title: Deletion Policy
      type: object
      properties:
        deletionPolicy:
          type: string
          default: Orphan
          enum:
            - Orphan
            - Delete
          title: Deletion Policy
    - title: Namespace
      type: object
      properties:
        namespace:
          type: string
          title: Namespace
    - title: Network
      type: object
      properties:
        network:
          type: string
          refType: compute.gcp.upbound.io/v1beta1/networks
          title: Network
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: Resource
                spec.api: compute.gcp.upbound.io/v1beta1/networks
    - title: Project Id
      type: object
      properties:
        projectId:
          type: string
          title: Project Id
    - title: Region
      type: object
      properties:
        region:
          type: string
          title: Region
    - title: Root Password
      type: object
      properties:
        rootPassword:
          type: string
          title: Root Password
    - title: Environemnt
      properties:
        environment:
          title: Environment
          type: string
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: Environment
  steps:
    - id: manifest
      name: Create Manifest
      action: catalog:write
      input:
        entity:
          apiVersion: ${{ parameters.group }}/${{ parameters.version }}
          kind: ${{ parameters.kind }}
          metadata:
            name: ${{ parameters.metadata.name }}
            annotations:
              backstage.io/title: ${{ parameters.metadata.annotations['backstage.io/title'] }}
              backstage.io/plural: ${{ parameters.metadata.annotations['backstage.io/plural'] }}
              backstage.io/entity-relations: "[\"${{ parameters.network | parseEntityRef |
                pick('name') }}\",\"${{ parameters.providerConfigRef.gcp.name |
                parseEntityRef | pick('name') }}\"]"
          spec:
            deletionPolicy: ${{ parameters.deletionPolicy }}
            namespace: ${{ parameters.namespace }}
            network: ${{ parameters.network }}
            projectId: ${{ parameters.projectId }}
            providerConfigRef: ${{ parameters.providerConfigRef }}
            region: ${{ parameters.region }}
            rootPassword: ${{ parameters.rootPassword }}
        filePath: ${{ parameters.metadata.name }}.${{ parameters.kind }}.${{
          parameters.group }}.${{ parameters.version }}.manifest.yaml
  output:
    text:
      - title: More information
        content: ${{ steps['publish'].output.remoteUrl }}